---
swagger: "2.0"
info:
  description: "uber + google "
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "user"
  description: "consultar tiempo estimado"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "https"
- "http"

paths:
  /user:
    post:
      tags:
      - "User"
      summary: "uso de los 2 microservices"
      description: ""
      operationId: "get_estimated"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "hello"
        required: true
        schema:
          $ref: "#/definitions/get_lat_lon"
      responses:
        200:
          description: "OK"
      x-swagger-router-controller: "swagger_server.controllers.user_controller"
      
definitions:
  get_lat_lon:
    type: "object"
    properties:
      address:
        type: "string"
      number:
        type: "string"
      comuna:
        type: "string"
      ciudad:
        type: "string"
      pais:
        type: "string"
    example:
      Inicio:
        address: "apoquindo"
        number: "4820"
        comuna: "las condes"
        ciudad: "santiago"
        pais: "chile"
      Destino:
        address: "Antonio varas"
        number: "880"
        comuna: "providencia"
        ciudad: "santiago"
        pais: "chile"
        
      
